import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Manrope } from "next/font/google";
import "./globals.css";
import ResponsiveNavbar from "@/components/Helper/Home/Navbar/ResponsiveNavbar";
import Provider from "@/components/HOC/Provider";

const font = Manrope({
  weight: ['200','300','400', '500','600', '700', '800'],
  subsets: ["latin"],
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${font.className} antialiased`}
      >
        <Provider>
        <ResponsiveNavbar/>
        {children}
        </Provider>
      </body>
    </html>
  );
}
